### ISSUE TITLE
Not able to inpu 

### ISSUE THREAD

**Issue by AnneSWarlaumont** [SeedlingsBabylab/idslabel#1] opened 2016-04-05 22:32 UTC
Hi, I am using the Mac app v0.0.3. I'm not seeing a way to input my IDS/Classifications or to change the speaker assignments. Is this just because that hasn't been added yet, or is it a bug in the version I have, or is it because I didn't install correctly? Screenshot included.

![image](https://cloud.githubusercontent.com/assets/8031754/14300153/56b073a0-fb43-11e5-9a39-5aff747f4a31.png)

**Comment by AnneSWarlaumont** [comment] 2016-04-05 22:32
How will we restart if we have to pause coding partway through?

**Comment by AnneSWarlaumont** [comment] 2016-04-05 22:33
It may help to order the buttons as follows: Previous Block, Play Block, Play Clip, Next Clip, since this is the order I'd usually click through.

**Comment by AnneSWarlaumont** [comment] 2016-04-05 22:37
It may help to add all the input selections that were done via the Load Clan File button, all the associated pop-ups, and the Load Audio File to the text displayed on the left side. So the WAV file that's being used, and the folder the clips are being saved to, and the output file would all be shown.

**Comment by AnneSWarlaumont** [comment] 2016-04-05 22:39
I'm not following the numbering of coded blocks. Maybe it has to do with when the "only load blocks with at least 1 FAN/MAN tier" checkbox has been clicked. It seems to say I've coded more blocks than I have, and when I hit "Previous Block", it skips some block #'s.

**Comment by andreiamatuni** [comment] 2016-04-05 23:23
Hey Anne,

To select the category labels for any given clip you need to press one of the classification keys, which are shortcuts on the keyboard. There is a list on the readme:
- General Keys
  - shift + a : load audio file
  - shift + c : load clan file
  - shift + enter : load random block
  - shift + \ : load previous block
  - cmd   + s : save classifications (Mac)
  - ctrl  + s : save classifications (Linux & Windows)
- Classification Keys
  - c : CDS
  - a : ADS
  - n : Child Noises
  - m : Multiple Addressee
  - r : Register Switch
  - j : Junk
- Clip Keys
  - up : previous clip
  - down: next clip
  - left          : previous clip
  - right         : next clip
  - space         : play clip
  - shift + space : play block

As well as a menu in the program itself under Help -> Show Shortcuts. When pressing the categorization keys, they will be assigned to whatever the current clip is. So for example, if you want to label a clip as being CDS, you would press "c", and if you want to label it as Child Noises, you would press "n". The goal was to make it so that switching between clips, playing, and categorizing them would be as fast as possible, hence the keyboard shortcuts. 

Regarding pausing halfway through and loading a partially labeled output file, this is something that's on the list of todo's, and will probably be in the next version, maybe the version after that.

I'll reorganize the buttons how you described. Also, it may be more convenient to just use the shortcut keys if you're going to be labeling a large file.

Adding all the load audio/clan and clips directory information to the GUI is a good idea. I'll add that in the next version. 

Regarding the numbering of the blocks, the "coded block #x" refers to the random sequence number. All the blocks start off in order, and then they're randomly shuffled. The coded block # refers to the index within that randomized series. If the "only load blocks with at least 1 FAN/MAN tier" option is checked you'll notice this number doesn't increase by 1 with each block load, since it might have to skip some. There's a bug I'm already aware of regarding loading previous blocks with this option checked. I'll try to have it resolved by the next version. The issue is keeping track of the order of loaded blocks when the "only load blocks..." option can be turned on/off at any point. It's only an issue because of the current way it keeps track of things.

**Comment by AnneSWarlaumont** [comment] 2016-04-05 23:50
Thanks, Andrei! I see it in the README now, I guess I skimmed the README or didn't think to read back to it. A quick fix to help other readme-skimming users in future might be to just add the shortcuts to the window, or add a note telling the user to go to the dropdown window to find the shortcuts for entering classification judgments. (We'll need to fine-tune what the classifications are of course, but I think we were waiting til after we'd all tested your program.)

So now on my second time testing I noticed that things worked for me for the first two blocks I did. Then it jumped ahead from coded block #2 to coded block #7 and the block wouldn't play for me. Loading more blocks and going back and forward a few times, it seems like the problem may be that blocks don't play after some blocks have been skipped (I do have the "only load blocks with at least 1 FAN/MAN" tier checked because it is the default). 

Thanks for all the info. about what your future to dos are. Great!

**Closed as completed** 2016-05-13 17:50 UTC
